### ISSUE TITLE
리드미 파일 추가하기

### ISSUE THREAD

**Issue by progh2** [miryung1018/muhanhyodo#2]
마크다운 형식을 사용하여 
프로젝트를 소개하는 리드미 파일을 만들어 넣기

**Comment by progh2** [comment]
프로젝트 폴더에 README.MD 파일을 생성하고 내용을 넣으면 됨.

**Comment by miryung1018** [comment]
![desert](https://cloud.githubusercontent.com/assets/14834089/10410366/68bbb956-6f7a-11e5-97aa-e24cf94d8afe.jpg)
