### ISSUE TITLE
앱 연동 테스트용 데이터 및 rest api 구현

### ISSUE THREAD

**Issue by progh2** [miryung1018/muhanhyodo#4]
php 기반 epi 라이브러리를 사용하여 테스트용 서버 코드 제작. 
알려준대로 라우터와 데이터 리턴 코드를 구현해 넣어주면 된다~

**Comment by miryung1018** [comment]
php 서버내용은 다른 저장소에 저장하고 서버 연동하는 코드만 넣기로
